version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 2345:5432
  keycloak:
#    image: quay.io/keycloak/keycloak:legacy
    image: koolwithk/keycloak-arm:16.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command:
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json

  mongodb:
#    image: mongodb/mongodb-community-server:6.0-ubi8
    image: arm64v8/mongo:4.2.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=twitter
    ports:
      - 27017:27017